### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Wiz-IO** [JeremyGrosser/pico_bsp#3]
Hi Jeremy,
I need help...

Can you compile all bootloaders from SDK
https://github.com/raspberrypi/pico-sdk/tree/master/src/rp2_common/boot_stage2

as this file
https://github.com/JeremyGrosser/pico_bsp/blob/master/src/boot2_w25q080.S

I am trying to porting SDK for PlatformIO ( Baremetal and Arduino )

Thanks
Georgi

**Comment by JeremyGrosser** [comment]
Sure, I can do that. For reference, here's what I ran against the built pico-sdk to generate these files:
```
mkdir boot2_asm
for i in pico-sdk/src/rp2_common/boot_stage2/*.S; do
    arm-eabi-gcc -Ipico-sdk/src/rp2040/hardware_regs/include -Ipico-sdk/src/rp2_common/pico_platform/include -Ipico-sdk/src/common/pico_base/include -Ipico-sdk/generated/pico_base -Ipico-sdk/src/rp2_common/boot_stage2/asminclude -E -o boot2_asm/$(basename $i) $i;
done
zip boot2_asm.zip boot2_asm/*
```

[boot2_asm.zip](https://github.com/JeremyGrosser/pico_bsp/files/5994346/boot2_asm.zip)

**Comment by JeremyGrosser** [comment]
If you were looking for the padded/checksummed versions of those.. I have no idea how to make pico-sdk generate that, I just used the default setup... It looks like it compiles the .S files into elf, then uses objcopy to turn that into binary that gets passed to `pico-sdk/src/rp2_common/boot_stage2/pad_checksum`

**Comment by Wiz-IO** [comment]
Hi 
thanks for answer
maybe is here
https://github.com/raspberrypi/pico-sdk/blob/master/src/rp2_common/boot_stage2/CMakeLists.txt#L3

yep, I need checksummed asm files... for now I use your boot2_w25q080.S
but no success for now... compilation is ok but no blink

if you have time - please compile ( I not install cmake... )
https://github.com/raspberrypi/pico-examples/tree/master/blink

Thanks

**Comment by JeremyGrosser** [comment]
You need to get your development environment working, I am not your compiler. I recommend you start with the excellent documentation that the Raspberry Pi Foundation has made available.

[Getting Started with Pico](https://datasheets.raspberrypi.org/pico/getting-started-with-pico.pdf)
[Pico C/C++ SDK](https://datasheets.raspberrypi.org/pico/raspberry-pi-pico-c-sdk.pdf)

**Comment by Wiz-IO** [comment]
sorry 
thanks

**Comment by Wiz-IO** [comment]
:)

![pio](https://user-images.githubusercontent.com/14574834/108198373-3660b180-7124-11eb-999a-2d104f941902.jpg)
